User.create(email: 'user@example.com', password: 'password')

Food.create(name: 'artichoke', group: 'vegetable')
Food.create(name: 'asparagus', group: 'vegetable')
Food.create(name: 'arugula', group: 'vegetable')
Food.create(name: 'avocados', group: 'vegetable')
Food.create(name: 'beets', group: 'vegetable')
Food.create(name: 'bell peppers', group: 'vegetable')
Food.create(name: 'bok choy', group: 'vegetable')
Food.create(name: 'brocolli', group: 'vegetable')
Food.create(name: 'broccoli rabe', group: 'vegetable')
Food.create(name: 'brussels sprouts', group: 'vegetable')
Food.create(name: 'cabbage', group: 'vegetable')
Food.create(name: 'carrots', group: 'vegetable')
Food.create(name: 'cauliflower', group: 'vegetable')
Food.create(name: 'celery', group: 'vegetable')
Food.create(name: 'celery root', group: 'vegetable')
Food.create(name: 'collards', group: 'vegetable')
Food.create(name: 'cucumbers', group: 'vegetable ')
Food.create(name: 'eggplant', group: 'vegetable ')
Food.create(name: 'endive', group: 'vegetable ')
Food.create(name: 'fennel', group: 'vegetable')
Food.create(name: 'fiddlehead ferns', group: 'vegetable')
Food.create(name: 'garlic', group: 'vegetable')
Food.create(name: 'green beans', group: 'vegetable')
Food.create(name: 'kale ', group:'vegetable')
Food.create(name: 'leeks', group: 'vegetable')
Food.create(name: 'mushrooms', group: 'vegetable')
Food.create(name: 'mustard greens', group: 'vegetable')
Food.create(name: 'olives', group: 'vegetable')
Food.create(name: 'onions', group: 'vegetable')
Food.create(name: 'parsnips', group: 'vegetable')
Food.create(name: 'peppers', group: 'vegetable')
Food.create(name: 'pumpkin', group: 'vegetable')
Food.create(name: 'radishes', group: 'vegetable')
Food.create(name: 'romaine lettuce', group: 'vegetable')
Food.create(name: 'sea vegetables', group: 'vegetable')
Food.create(name: 'spinach', group: 'vegetable')
Food.create(name: 'squash', group: 'vegetable')
Food.create(name: 'swiss chard', group: 'vegetable')
Food.create(name: 'tomatoes', group: 'vegetable')
Food.create(name: 'turnip greens', group: 'vegetable')
Food.create(name: 'water cress', group: 'vegetable')
Food.create(name: 'sweet potatoes', group: 'vegetable')
Food.create(name: 'yams', group: 'vegetable')
Food.create(name: 'potatoes', group: 'vegetable')
Food.create(name: 'wild rice', group: 'vegetable')
Food.create(name: 'anchovies', group: 'fish')
Food.create(name: 'bass', group: 'fish')
Food.create(name: 'cod', group: 'fish')
Food.create(name: 'eel', group: 'fish')
Food.create(name: 'haddock', group: 'fish')
Food.create(name: 'halibut', group: 'fish')
Food.create(name: 'herring', group: 'fish')
Food.create(name: 'mackerel', group: 'fish')
Food.create(name: 'mahi mahi', group: 'fish')
Food.create(name: 'mullet', group: 'fish')
Food.create(name: 'northern pilke', group: 'fish')
Food.create(name: 'orange roughy', group: 'fish')
Food.create(name: 'perch', group: 'fish')
Food.create(name: 'red snapper', group: 'fish')
Food.create(name: 'rockfish', group: 'fish')
Food.create(name: 'salmon', group: 'fish')
Food.create(name: 'sardines', group: 'fish')
Food.create(name: 'tilapia', group: 'fish')
Food.create(name: 'tuna', group: 'fish')
Food.create(name: 'walleye', group: 'fish')
Food.create(name: 'abalone', group: 'fish')
Food.create(name: 'clams', group: 'fish')
Food.create(name: 'crayfish', group: 'fish')
Food.create(name: 'lobster', group: 'fish')
Food.create(name: 'mussles', group: 'fish')
Food.create(name: 'oysters', group: 'fish')
Food.create(name: 'prawns', group: 'fish')
Food.create(name: 'scallops', group: 'fish')
Food.create(name: 'shrimp', group: 'fish')
Food.create(name: 'chicken', group: 'meat')
Food.create(name: 'goat', group: 'meat')
Food.create(name: 'pork', group: 'meat')
Food.create(name: 'lamb', group: 'meat')
Food.create(name: 'alligator', group: 'meat')
Food.create(name: 'caribou', group: 'meat')
Food.create(name: 'bear', group: 'meat')
Food.create(name: 'buffalo', group: 'meat')
Food.create(name: 'duck', group: 'meat')
Food.create(name: 'emu', group: 'meat')
Food.create(name: 'goose', group: 'meat')
Food.create(name: 'pheasant', group: 'meat')
Food.create(name: 'kagaroo', group: 'meat')
Food.create(name: 'ostrich', group: 'meat')
Food.create(name: 'rabbit', group: 'meat')
Food.create(name: 'snakes', group: 'meat')
Food.create(name: 'turkey', group: 'meat')
Food.create(name: 'venison', group: 'meat')
Food.create(name: 'elk', group: 'meat')
Food.create(name: 'quail', group: 'meat')
Food.create(name: 'eggs', group: 'meat')
Food.create(name: 'almonds', group: 'nuts')
Food.create(name: 'brazil nuts', group: 'nuts')
Food.create(name: 'hazel nuts', group: 'nuts')
Food.create(name: 'hempseeds', group: 'nuts')
Food.create(name: 'macadamias', group: 'nuts')
Food.create(name: 'pecans', group: 'nuts')
Food.create(name: 'pine nuts', group: 'nuts')
Food.create(name: 'pistachios', group: 'nuts')
Food.create(name: 'pumpkin seeds', group: 'nuts')
Food.create(name: 'seasame seeds', group: 'nuts')
Food.create(name: 'sunflower seeds', group: 'nuts')
Food.create(name: 'walnuts', group: 'nuts')
Food.create(name: ' avacodo oil ', group: 'fats')
Food.create(name: 'butter ', group: 'fats')
Food.create(name: 'coconut oil', group: 'fats')
Food.create(name: 'macadamia oil', group: 'fats')
Food.create(name: 'olive oil', group: 'fats')
Food.create(name: 'seasame oil', group: 'fats')
Food.create(name: 'lard', group: 'fats')
Food.create(name: 'unprocessed palm oil', group: 'fats')
Food.create(name: 'walnut oil', group: 'fats')
Food.create(name: 'blueberries', group: 'fruits')
Food.create(name: 'boysenberries', group: 'fruits')
Food.create(name: 'cranberries', group: 'fruits')
Food.create(name: 'gooseberries', group: 'fruits')
Food.create(name: 'raspberries', group: 'fruits')
Food.create(name: 'apple', group: 'fruits')
Food.create(name: 'cantalope', group: 'fruits')
Food.create(name: 'coconut', group: 'fruits')
Food.create(name: 'grapefruit', group: 'fruits')
Food.create(name: 'kiwi', group: 'fruits')
Food.create(name: 'lime', group: 'fruits')
Food.create(name: 'nectarine', group: 'fruits')
Food.create(name: 'orange', group: 'fruits')
Food.create(name: ' anise ', group: 'spices')
Food.create(name: 'basil', group: 'spices')
Food.create(name: 'black pepper', group: 'spices')
Food.create(name: 'cayenne pepper', group: 'spices')
Food.create(name: 'cilantro', group: 'spices')
Food.create(name: 'coriander seeds', group: 'spices')
Food.create(name: 'cinnamon', group: 'spices')
Food.create(name: 'cloves', group: 'spices')
Food.create(name: 'cumin', group: 'spices')
Food.create(name: 'dill', group: 'spices')
Food.create(name: 'fennel', group: 'spices')
Food.create(name: 'ginger', group: 'spices')
Food.create(name: 'mint', group: 'spices')
Food.create(name: 'mustard seeds', group: 'spices')
Food.create(name: 'nutmeg', group: 'spices')
Food.create(name: 'oregano', group: 'spices')
Food.create(name: 'paprika', group: 'spices')
Food.create(name: 'peppermint', group: 'spices')
Food.create(name: 'rosemary', group: 'spices')
Food.create(name: 'sage', group: 'spices')
Food.create(name: 'stevia', group: 'spices')
Food.create(name: 'tarragon', group: 'spices')
Food.create(name: 'thyme', group: 'spices')
Food.create(name: 'tumeric', group: 'spices')
