User.create(email: 'user@example.com', password: 'password')

Food.create(name: 'artichoke', group: 'vegetable')
Food.create(name: 'avocados', group: 'vegetable')
Food.create(name: 'peppers', group: 'vegetable')
Food.create(name: 'carrots', group: 'vegetable')
Food.create(name: 'mushrooms', group: 'vegetable')
Food.create(name: 'tomatoes', group: 'vegetable')
Food.create(name: 'sweet potatoes', group: 'vegetable')
Food.create(name: 'cod', group: 'fish')
Food.create(name: 'halibut', group: 'fish')
Food.create(name: 'mahi mahi', group: 'fish')
Food.create(name: 'salmon', group: 'fish')
Food.create(name: 'tilapia', group: 'fish')
Food.create(name: 'tuna', group: 'fish')
Food.create(name: 'shrimp', group: 'fish')
Food.create(name: 'chicken', group: 'meat')
Food.create(name: 'pork', group: 'meat')
Food.create(name: 'lamb', group: 'meat')
Food.create(name: 'turkey', group: 'meat')
Food.create(name: 'eggs', group: 'meat')
Food.create(name: 'almonds', group: 'nuts')
Food.create(name: 'pecans', group: 'nuts')
Food.create(name: 'pistachios', group: 'nuts')
Food.create(name: 'brazil nuts', group: 'nuts')
Food.create(name: 'seaseme seeds', group: 'nuts')
Food.create(name: 'butter ', group: 'fats')
Food.create(name: 'coconut oil', group: 'fats')
Food.create(name: 'olive oil', group: 'fats')
Food.create(name: 'blueberries', group: 'fruits')
Food.create(name: 'raspberries', group: 'fruits')
Food.create(name: 'apple', group: 'fruits')
Food.create(name: 'grapefruit', group: 'fruits')
Food.create(name: 'orange', group: 'fruits')
Food.create(name: 'basil', group: 'spices')
Food.create(name: 'black pepper', group: 'spices')
Food.create(name: 'cinnamon', group: 'spices')
Food.create(name: 'ginger', group: 'spices')
